package gov.aas.pagibig.webservice.core;
// Generated Nov 13, 2014 10:28:59 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbGetPtnCreditMemo generated by hbm2java
 */
@Entity
@Table(name="tb_get_ptn_credit_memo"
    ,catalog="db_integ_aas"
)
public class TbGetPtnCreditMemo  implements java.io.Serializable {


     private String payTrackNum;
     private String payorName;
     private String brCode;
     private Date sysDate;
     private String payorId;
     private String payorAddress;
     private String creditMemoNum;
     private Date creditMemoDate;
     private String partic;
     private BigDecimal amt;

    public TbGetPtnCreditMemo() {
    }

    public TbGetPtnCreditMemo(String payTrackNum, String payorName, String brCode, Date sysDate, String payorId, String payorAddress, String creditMemoNum, Date creditMemoDate, String partic, BigDecimal amt) {
       this.payTrackNum = payTrackNum;
       this.payorName = payorName;
       this.brCode = brCode;
       this.sysDate = sysDate;
       this.payorId = payorId;
       this.payorAddress = payorAddress;
       this.creditMemoNum = creditMemoNum;
       this.creditMemoDate = creditMemoDate;
       this.partic = partic;
       this.amt = amt;
    }
   
     @Id 
    
    @Column(name="pay_track_num", unique=true, nullable=false, length=50)
    public String getPayTrackNum() {
        return this.payTrackNum;
    }
    
    public void setPayTrackNum(String payTrackNum) {
        this.payTrackNum = payTrackNum;
    }
    
    @Column(name="payor_name", nullable=false, length=100)
    public String getPayorName() {
        return this.payorName;
    }
    
    public void setPayorName(String payorName) {
        this.payorName = payorName;
    }
    
    @Column(name="br_code", nullable=false, length=20)
    public String getBrCode() {
        return this.brCode;
    }
    
    public void setBrCode(String brCode) {
        this.brCode = brCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sys_date", nullable=false, length=10)
    public Date getSysDate() {
        return this.sysDate;
    }
    
    public void setSysDate(Date sysDate) {
        this.sysDate = sysDate;
    }
    
    @Column(name="payor_id", nullable=false, length=50)
    public String getPayorId() {
        return this.payorId;
    }
    
    public void setPayorId(String payorId) {
        this.payorId = payorId;
    }
    
    @Column(name="payor_address", nullable=false, length=100)
    public String getPayorAddress() {
        return this.payorAddress;
    }
    
    public void setPayorAddress(String payorAddress) {
        this.payorAddress = payorAddress;
    }
    
    @Column(name="credit_memo_num", nullable=false, length=50)
    public String getCreditMemoNum() {
        return this.creditMemoNum;
    }
    
    public void setCreditMemoNum(String creditMemoNum) {
        this.creditMemoNum = creditMemoNum;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="credit_memo_date", nullable=false, length=10)
    public Date getCreditMemoDate() {
        return this.creditMemoDate;
    }
    
    public void setCreditMemoDate(Date creditMemoDate) {
        this.creditMemoDate = creditMemoDate;
    }
    
    @Column(name="partic", nullable=false, length=100)
    public String getPartic() {
        return this.partic;
    }
    
    public void setPartic(String partic) {
        this.partic = partic;
    }
    
    @Column(name="amt", nullable=false, precision=15)
    public BigDecimal getAmt() {
        return this.amt;
    }
    
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }




}


