package gov.aas.pagibig.webservice.core;
// Generated Nov 13, 2014 10:28:59 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbInsertPofDetails generated by hbm2java
 */
@Entity
@Table(name="tb_insert_pof_details"
    ,catalog="db_integ_aas"
)
public class TbInsertPofDetails  implements java.io.Serializable {


     private String pofNo;
     private String accountTypeCode;
     private String accountType;
     private BigDecimal amount;

    public TbInsertPofDetails() {
    }

    public TbInsertPofDetails(String pofNo, String accountTypeCode, String accountType, BigDecimal amount) {
       this.pofNo = pofNo;
       this.accountTypeCode = accountTypeCode;
       this.accountType = accountType;
       this.amount = amount;
    }
   
     @Id 
    
    @Column(name="pof_no", unique=true, nullable=false, length=50)
    public String getPofNo() {
        return this.pofNo;
    }
    
    public void setPofNo(String pofNo) {
        this.pofNo = pofNo;
    }
    
    @Column(name="account_type_code", nullable=false, length=50)
    public String getAccountTypeCode() {
        return this.accountTypeCode;
    }
    
    public void setAccountTypeCode(String accountTypeCode) {
        this.accountTypeCode = accountTypeCode;
    }
    
    @Column(name="account_type", nullable=false, length=200)
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    
    @Column(name="amount", nullable=false, precision=20)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


