package gov.aas.pagibig.webservice.core;
// Generated Oct 21, 2014 9:52:07 AM by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.GeneratedValue;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;	
/**
 * TBLForeClosedProperty generated by hbm2java
 */
/**
 * TbGetPtnPaymDetails generated by hbm2java
 */
@Entity
@Table(name="tb_get_ptn_paym_details"
, uniqueConstraints = @UniqueConstraint(columnNames="paym_track_num") )
@NamedQueries( @NamedQuery( name = "TBLGetPtnPaymDetails.getDetails", query = "SELECT tbl FROM TBLGetPtnPaymDetails tbl WHERE tbl.paymTrackNum = :paymTrackNum " )
)
public class TBLGetPtnPaymDetails  implements java.io.Serializable {


     private String paymTrackNum;
     private String accTypeCode;
     private String accTypeDesc;
     private String accNo;
     private String debitMemo;
     private String period;
     private String payAllo;
     private BigDecimal amount;

    public TBLGetPtnPaymDetails() {
    }

	
    public TBLGetPtnPaymDetails(String paymTrackNum, String accTypeCode, String accTypeDesc, String accNo, BigDecimal amount) {
        this.paymTrackNum = paymTrackNum;
        this.accTypeCode = accTypeCode;
        this.accTypeDesc = accTypeDesc;
        this.accNo = accNo;
        this.amount = amount;
    }
    public TBLGetPtnPaymDetails(String paymTrackNum, String accTypeCode, String accTypeDesc, String accNo, String debitMemo, String period, String payAllo, BigDecimal amount) {
       this.paymTrackNum = paymTrackNum;
       this.accTypeCode = accTypeCode;
       this.accTypeDesc = accTypeDesc;
       this.accNo = accNo;
       this.debitMemo = debitMemo;
       this.period = period;
       this.payAllo = payAllo;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="paym_track_num", unique=true, nullable=false, length=50)
    public String getPaymTrackNum() {
        return this.paymTrackNum;
    }
    
    public void setPaymTrackNum(String paymTrackNum) {
        this.paymTrackNum = paymTrackNum;
    }
    
    @Column(name="acc_type_code", nullable=false, length=50)
    public String getAccTypeCode() {
        return this.accTypeCode;
    }
    
    public void setAccTypeCode(String accTypeCode) {
        this.accTypeCode = accTypeCode;
    }
    
    @Column(name="acc_type_desc", nullable=false, length=100)
    public String getAccTypeDesc() {
        return this.accTypeDesc;
    }
    
    public void setAccTypeDesc(String accTypeDesc) {
        this.accTypeDesc = accTypeDesc;
    }
    
    @Column(name="acc_no", nullable=false, length=25)
    public String getAccNo() {
        return this.accNo;
    }
    
    public void setAccNo(String accNo) {
        this.accNo = accNo;
    }
    
    @Column(name="debit_memo", length=100)
    public String getDebitMemo() {
        return this.debitMemo;
    }
    
    public void setDebitMemo(String debitMemo) {
        this.debitMemo = debitMemo;
    }
    
    @Column(name="period", length=100)
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }
    
    @Column(name="pay_allo", length=100)
    public String getPayAllo() {
        return this.payAllo;
    }
    
    public void setPayAllo(String payAllo) {
        this.payAllo = payAllo;
    }
    
    @Column(name="amount", nullable=false, precision=15)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


