package gov.aas.pagibig.webservice.core;
// Generated Nov 13, 2014 10:28:59 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbLogs generated by hbm2java
 */
@Entity
@Table(name="tb_logs"
    ,catalog="db_integ_aas"
)
public class TbLogs  implements java.io.Serializable {


     private TbLogsId id;
     private TbUsers tbUsers;
     private Date timeIn;

    public TbLogs() {
    }

	
    public TbLogs(TbLogsId id, TbUsers tbUsers) {
        this.id = id;
        this.tbUsers = tbUsers;
    }
    public TbLogs(TbLogsId id, TbUsers tbUsers, Date timeIn) {
       this.id = id;
       this.tbUsers = tbUsers;
       this.timeIn = timeIn;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public TbLogsId getId() {
        return this.id;
    }
    
    public void setId(TbLogsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public TbUsers getTbUsers() {
        return this.tbUsers;
    }
    
    public void setTbUsers(TbUsers tbUsers) {
        this.tbUsers = tbUsers;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_in", length=19)
    public Date getTimeIn() {
        return this.timeIn;
    }
    
    public void setTimeIn(Date timeIn) {
        this.timeIn = timeIn;
    }




}


