package gov.aas.pagibig.webservice.core;
// Generated Nov 20, 2014 5:59:56 PM by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.GeneratedValue;
import javax.persistence.UniqueConstraint;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * TBLUpdatePofStatus generated by hbm2java
 */
@Entity
@Table(name="tb_update_pof_status"
    , uniqueConstraints = @UniqueConstraint(columnNames="pof_no") 
)
@NamedQueries
({@NamedQuery( name = "TBLUpdatePofStatus.updPOFStat", query = "SELECT tbl FROM TBLUpdatePofStatus tbl WHERE tbl.pofNo=:pofNo" )
, @NamedQuery( name = "TBLUpdatePofStatus.checkPofStat", query = "SELECT tbl FROM TBLUpdatePofStatus tbl WHERE tbl.pofNo=:pofNo AND tbl.payorName=:payorName AND tbl.src=:src" )
})   
public class TBLUpdatePofStatus  implements java.io.Serializable {


     private String pofNo;
     private String payorName;
     private String pfrNo;
     private String src;
     private float totalAmt;
     private String generatedBy;
     private Date dateGenerated;
     private String status;
     private Date datePaym;
     private String receivingUnit;
     private int ofcNo;

    public TBLUpdatePofStatus() {
    }

	
    public TBLUpdatePofStatus(String pofNo, String payorName, String pfrNo, String src, float totalAmt, String status, Date datePaym, String receivingUnit, int ofcNo) {
        this.pofNo = pofNo;
        this.payorName = payorName;
        this.pfrNo = pfrNo;
        this.src = src;
        this.totalAmt = totalAmt;
        this.status = status;
        this.datePaym = datePaym;
        this.receivingUnit = receivingUnit;
        this.ofcNo = ofcNo;
    }
    public TBLUpdatePofStatus(String pofNo, String payorName, String pfrNo, String src, float totalAmt, String generatedBy, Date dateGenerated, String status, Date datePaym, String receivingUnit, int ofcNo) {
       this.pofNo = pofNo;
       this.payorName = payorName;
       this.pfrNo = pfrNo;
       this.src = src;
       this.totalAmt = totalAmt;
       this.generatedBy = generatedBy;
       this.dateGenerated = dateGenerated;
       this.status = status;
       this.datePaym = datePaym;
       this.receivingUnit = receivingUnit;
       this.ofcNo = ofcNo;
    }
   
     @Id
    
    @Column(name="pof_no", unique=true, nullable=false, length=32)
    public String getPofNo() {
        return this.pofNo;
    }
    
    public void setPofNo(String pofNo) {
        this.pofNo = pofNo;
    }
    
    @Column(name="payor_name", nullable=false, length=100)
    public String getPayorName() {
        return this.payorName;
    }
    
    public void setPayorName(String payorName) {
        this.payorName = payorName;
    }
    
    @Column(name="pfr_no", nullable=false, length=32)
    public String getPfrNo() {
        return this.pfrNo;
    }
    
    public void setPfrNo(String pfrNo) {
        this.pfrNo = pfrNo;
    }
    
    @Column(name="src", nullable=false, length=50)
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }
    
    @Column(name="total_amt", nullable=false, precision=12, scale=0)
    public float getTotalAmt() {
        return this.totalAmt;
    }
    
    public void setTotalAmt(float totalAmt) {
        this.totalAmt = totalAmt;
    }
    
    @Column(name="generated_by", length=50)
    public String getGeneratedBy() {
        return this.generatedBy;
    }
    
    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_generated", length=10)
    public Date getDateGenerated() {
        return this.dateGenerated;
    }
    
    public void setDateGenerated(Date dateGenerated) {
        this.dateGenerated = dateGenerated;
    }
    
    @Column(name="status", nullable=false, length=3)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_paym", nullable=false, length=10)
    public Date getDatePaym() {
        return this.datePaym;
    }
    
    public void setDatePaym(Date datePaym) {
        this.datePaym = datePaym;
    }
    
    @Column(name="receiving_unit", nullable=false, length=50)
    public String getReceivingUnit() {
        return this.receivingUnit;
    }
    
    public void setReceivingUnit(String receivingUnit) {
        this.receivingUnit = receivingUnit;
    }
    
    @Column(name="ofc_no", nullable=false)
    public int getOfcNo() {
        return this.ofcNo;
    }
    
    public void setOfcNo(int ofcNo) {
        this.ofcNo = ofcNo;
    }




}


