package gov.aas.pagibig.webservice.core;
// Generated Nov 13, 2014 10:28:59 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbUsers generated by hbm2java
 */
@Entity
@Table(name="tb_users"
    ,catalog="db_integ_aas"
)
public class TbUsers  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private int systemId;
     private Set<TbLogs> tbLogses = new HashSet<TbLogs>(0);
     private Set<TbAuditTrail> tbAuditTrails = new HashSet<TbAuditTrail>(0);

    public TbUsers() {
    }

	
    public TbUsers(int id, String username, String password, int systemId) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.systemId = systemId;
    }
    public TbUsers(int id, String username, String password, int systemId, Set<TbLogs> tbLogses, Set<TbAuditTrail> tbAuditTrails) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.systemId = systemId;
       this.tbLogses = tbLogses;
       this.tbAuditTrails = tbAuditTrails;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="system_id", nullable=false)
    public int getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbUsers")
    public Set<TbLogs> getTbLogses() {
        return this.tbLogses;
    }
    
    public void setTbLogses(Set<TbLogs> tbLogses) {
        this.tbLogses = tbLogses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbUsers")
    public Set<TbAuditTrail> getTbAuditTrails() {
        return this.tbAuditTrails;
    }
    
    public void setTbAuditTrails(Set<TbAuditTrail> tbAuditTrails) {
        this.tbAuditTrails = tbAuditTrails;
    }




}


