package gov.aas.pagibig.webservice.core;
// Generated Nov 13, 2014 10:28:59 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbValidateForeclosePaym generated by hbm2java
 */
@Entity
@Table(name="tb_validate_foreclose_paym"
    ,catalog="db_integ_aas"
)
public class TbValidateForeclosePaym  implements java.io.Serializable {


     private String mid;
     private int status;
     private String propNo;
     private Integer yearOfForClosure;

    public TbValidateForeclosePaym() {
    }

	
    public TbValidateForeclosePaym(String mid, int status, String propNo) {
        this.mid = mid;
        this.status = status;
        this.propNo = propNo;
    }
    public TbValidateForeclosePaym(String mid, int status, String propNo, Integer yearOfForClosure) {
       this.mid = mid;
       this.status = status;
       this.propNo = propNo;
       this.yearOfForClosure = yearOfForClosure;
    }
   
     @Id 
    
    @Column(name="Mid", unique=true, nullable=false, length=32)
    public String getMid() {
        return this.mid;
    }
    
    public void setMid(String mid) {
        this.mid = mid;
    }
    
    @Column(name="Status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    
    @Column(name="Prop_No", nullable=false, length=30)
    public String getPropNo() {
        return this.propNo;
    }
    
    public void setPropNo(String propNo) {
        this.propNo = propNo;
    }
    
    @Column(name="yearOfForClosure")
    public Integer getYearOfForClosure() {
        return this.yearOfForClosure;
    }
    
    public void setYearOfForClosure(Integer yearOfForClosure) {
        this.yearOfForClosure = yearOfForClosure;
    }




}


