//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.27 at 04:46:55 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.aas.pagibig.schema.ErrorType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pof_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pfr_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date_paym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="total_amt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiving_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ofc_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error" type="{http://schema.pagibig.aas.gov}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pofNo",
    "pfrNo",
    "datePaym",
    "totalAmt",
    "receivingUnit",
    "ofcNo",
    "error"
})
@XmlRootElement(name = "integ_otc_check_pof_statusResponse")
public class IntegOtcCheckPofStatusResponse {

    @XmlElement(name = "pof_no", required = true)
    protected String pofNo;
    @XmlElement(name = "pfr_no", required = true)
    protected String pfrNo;
    @XmlElement(name = "date_paym", required = true)
    protected String datePaym;
    @XmlElement(name = "total_amt", required = true)
    protected String totalAmt;
    @XmlElement(name = "receiving_unit", required = true)
    protected String receivingUnit;
    @XmlElement(name = "ofc_no", required = true)
    protected String ofcNo;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the pofNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPofNo() {
        return pofNo;
    }

    /**
     * Sets the value of the pofNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPofNo(String value) {
        this.pofNo = value;
    }

    /**
     * Gets the value of the pfrNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfrNo() {
        return pfrNo;
    }

    /**
     * Sets the value of the pfrNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfrNo(String value) {
        this.pfrNo = value;
    }

    /**
     * Gets the value of the datePaym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatePaym() {
        return datePaym;
    }

    /**
     * Sets the value of the datePaym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatePaym(String value) {
        this.datePaym = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAmt(String value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the receivingUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingUnit() {
        return receivingUnit;
    }

    /**
     * Sets the value of the receivingUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingUnit(String value) {
        this.receivingUnit = value;
    }

    /**
     * Gets the value of the ofcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfcNo() {
        return ofcNo;
    }

    /**
     * Sets the value of the ofcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfcNo(String value) {
        this.ofcNo = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
