//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 05:31:12 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acctg_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="account_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="journal_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="references_or_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branch_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctgDate",
    "accountType",
    "segment1",
    "segment2",
    "segment3",
    "segment4",
    "segment5",
    "segment6",
    "segment7",
    "segment8",
    "segment9",
    "segment10",
    "journalName",
    "categoryName",
    "currencyCode",
    "amount",
    "referencesOrDescription",
    "branchCode",
    "transactionId"
})
@XmlRootElement(name = "integ_gl_post_journal_entries_to_gl_request_list")
public class IntegGlPostJournalEntriesToGlRequestList {

    @XmlElement(name = "acctg_date", required = true)
    protected String acctgDate;
    @XmlElement(name = "account_type", required = true)
    protected String accountType;
    @XmlElement(required = true)
    protected String segment1;
    @XmlElement(required = true)
    protected String segment2;
    @XmlElement(required = true)
    protected String segment3;
    @XmlElement(required = true)
    protected String segment4;
    @XmlElement(required = true)
    protected String segment5;
    @XmlElement(required = true)
    protected String segment6;
    @XmlElement(required = true)
    protected String segment7;
    @XmlElement(required = true)
    protected String segment8;
    @XmlElement(required = true)
    protected String segment9;
    @XmlElement(required = true)
    protected String segment10;
    @XmlElement(name = "journal_name", required = true)
    protected String journalName;
    @XmlElement(name = "category_name", required = true)
    protected String categoryName;
    @XmlElement(name = "currency_code", required = true)
    protected String currencyCode;
    @XmlElement(required = true)
    protected String amount;
    @XmlElement(name = "references_or_description", required = true)
    protected String referencesOrDescription;
    @XmlElement(name = "branch_code", required = true)
    protected String branchCode;
    @XmlElement(name = "transaction_id", required = true)
    protected String transactionId;

    /**
     * Gets the value of the acctgDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctgDate() {
        return acctgDate;
    }

    /**
     * Sets the value of the acctgDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctgDate(String value) {
        this.acctgDate = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the segment1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment1() {
        return segment1;
    }

    /**
     * Sets the value of the segment1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment1(String value) {
        this.segment1 = value;
    }

    /**
     * Gets the value of the segment2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment2() {
        return segment2;
    }

    /**
     * Sets the value of the segment2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment2(String value) {
        this.segment2 = value;
    }

    /**
     * Gets the value of the segment3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment3() {
        return segment3;
    }

    /**
     * Sets the value of the segment3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment3(String value) {
        this.segment3 = value;
    }

    /**
     * Gets the value of the segment4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment4() {
        return segment4;
    }

    /**
     * Sets the value of the segment4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment4(String value) {
        this.segment4 = value;
    }

    /**
     * Gets the value of the segment5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment5() {
        return segment5;
    }

    /**
     * Sets the value of the segment5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment5(String value) {
        this.segment5 = value;
    }

    /**
     * Gets the value of the segment6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment6() {
        return segment6;
    }

    /**
     * Sets the value of the segment6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment6(String value) {
        this.segment6 = value;
    }

    /**
     * Gets the value of the segment7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment7() {
        return segment7;
    }

    /**
     * Sets the value of the segment7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment7(String value) {
        this.segment7 = value;
    }

    /**
     * Gets the value of the segment8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment8() {
        return segment8;
    }

    /**
     * Sets the value of the segment8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment8(String value) {
        this.segment8 = value;
    }

    /**
     * Gets the value of the segment9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment9() {
        return segment9;
    }

    /**
     * Sets the value of the segment9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment9(String value) {
        this.segment9 = value;
    }

    /**
     * Gets the value of the segment10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment10() {
        return segment10;
    }

    /**
     * Sets the value of the segment10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment10(String value) {
        this.segment10 = value;
    }

    /**
     * Gets the value of the journalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalName() {
        return journalName;
    }

    /**
     * Sets the value of the journalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalName(String value) {
        this.journalName = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the referencesOrDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencesOrDescription() {
        return referencesOrDescription;
    }

    /**
     * Sets the value of the referencesOrDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencesOrDescription(String value) {
        this.referencesOrDescription = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

}
