//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 06:31:22 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hdr_receipt_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_receipt_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="hdr_amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="hdr_gl_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="hdr_receipt_method_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_customer_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_location_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_customer_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_location_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_currency_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dtl_invoice_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dtl_receivable_activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dtl_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dtl_bank_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dtl_check_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branch_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hdrReceiptNo",
    "hdrReceiptDate",
    "hdrAmount",
    "hdrGlDate",
    "hdrReceiptMethodName",
    "hdrCustomerNumber",
    "hdrLocationCode",
    "hdrCustomerName",
    "hdrLocationName",
    "hdrCurrencyCode",
    "dtlInvoiceNumber",
    "dtlReceivableActivity",
    "dtlDescription",
    "dtlBankName",
    "dtlCheckNumber",
    "branchCode",
    "transactionId"
})
@XmlRootElement(name = "integ_otc_post_collections_and_other_collections_list")
public class IntegOtcPostCollectionsAndOtherCollectionsList {

    @XmlElement(name = "hdr_receipt_no", required = true)
    protected String hdrReceiptNo;
    @XmlElement(name = "hdr_receipt_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hdrReceiptDate;
    @XmlElement(name = "hdr_amount")
    protected double hdrAmount;
    @XmlElement(name = "hdr_gl_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar hdrGlDate;
    @XmlElement(name = "hdr_receipt_method_name", required = true)
    protected String hdrReceiptMethodName;
    @XmlElement(name = "hdr_customer_number", required = true)
    protected String hdrCustomerNumber;
    @XmlElement(name = "hdr_location_code", required = true)
    protected String hdrLocationCode;
    @XmlElement(name = "hdr_customer_name", required = true)
    protected String hdrCustomerName;
    @XmlElement(name = "hdr_location_name", required = true)
    protected String hdrLocationName;
    @XmlElement(name = "hdr_currency_code", required = true)
    protected String hdrCurrencyCode;
    @XmlElement(name = "dtl_invoice_number", required = true)
    protected String dtlInvoiceNumber;
    @XmlElement(name = "dtl_receivable_activity", required = true)
    protected String dtlReceivableActivity;
    @XmlElement(name = "dtl_description", required = true)
    protected String dtlDescription;
    @XmlElement(name = "dtl_bank_name", required = true)
    protected String dtlBankName;
    @XmlElement(name = "dtl_check_number", required = true)
    protected String dtlCheckNumber;
    @XmlElement(name = "branch_code", required = true)
    protected String branchCode;
    @XmlElement(name = "transaction_id", required = true)
    protected String transactionId;

    /**
     * Gets the value of the hdrReceiptNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrReceiptNo() {
        return hdrReceiptNo;
    }

    /**
     * Sets the value of the hdrReceiptNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrReceiptNo(String value) {
        this.hdrReceiptNo = value;
    }

    /**
     * Gets the value of the hdrReceiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHdrReceiptDate() {
        return hdrReceiptDate;
    }

    /**
     * Sets the value of the hdrReceiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHdrReceiptDate(XMLGregorianCalendar value) {
        this.hdrReceiptDate = value;
    }

    /**
     * Gets the value of the hdrAmount property.
     * 
     */
    public double getHdrAmount() {
        return hdrAmount;
    }

    /**
     * Sets the value of the hdrAmount property.
     * 
     */
    public void setHdrAmount(double value) {
        this.hdrAmount = value;
    }

    /**
     * Gets the value of the hdrGlDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHdrGlDate() {
        return hdrGlDate;
    }

    /**
     * Sets the value of the hdrGlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHdrGlDate(XMLGregorianCalendar value) {
        this.hdrGlDate = value;
    }

    /**
     * Gets the value of the hdrReceiptMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrReceiptMethodName() {
        return hdrReceiptMethodName;
    }

    /**
     * Sets the value of the hdrReceiptMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrReceiptMethodName(String value) {
        this.hdrReceiptMethodName = value;
    }

    /**
     * Gets the value of the hdrCustomerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrCustomerNumber() {
        return hdrCustomerNumber;
    }

    /**
     * Sets the value of the hdrCustomerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrCustomerNumber(String value) {
        this.hdrCustomerNumber = value;
    }

    /**
     * Gets the value of the hdrLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrLocationCode() {
        return hdrLocationCode;
    }

    /**
     * Sets the value of the hdrLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrLocationCode(String value) {
        this.hdrLocationCode = value;
    }

    /**
     * Gets the value of the hdrCustomerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrCustomerName() {
        return hdrCustomerName;
    }

    /**
     * Sets the value of the hdrCustomerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrCustomerName(String value) {
        this.hdrCustomerName = value;
    }

    /**
     * Gets the value of the hdrLocationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrLocationName() {
        return hdrLocationName;
    }

    /**
     * Sets the value of the hdrLocationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrLocationName(String value) {
        this.hdrLocationName = value;
    }

    /**
     * Gets the value of the hdrCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrCurrencyCode() {
        return hdrCurrencyCode;
    }

    /**
     * Sets the value of the hdrCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrCurrencyCode(String value) {
        this.hdrCurrencyCode = value;
    }

    /**
     * Gets the value of the dtlInvoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtlInvoiceNumber() {
        return dtlInvoiceNumber;
    }

    /**
     * Sets the value of the dtlInvoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtlInvoiceNumber(String value) {
        this.dtlInvoiceNumber = value;
    }

    /**
     * Gets the value of the dtlReceivableActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtlReceivableActivity() {
        return dtlReceivableActivity;
    }

    /**
     * Sets the value of the dtlReceivableActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtlReceivableActivity(String value) {
        this.dtlReceivableActivity = value;
    }

    /**
     * Gets the value of the dtlDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtlDescription() {
        return dtlDescription;
    }

    /**
     * Sets the value of the dtlDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtlDescription(String value) {
        this.dtlDescription = value;
    }

    /**
     * Gets the value of the dtlBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtlBankName() {
        return dtlBankName;
    }

    /**
     * Sets the value of the dtlBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtlBankName(String value) {
        this.dtlBankName = value;
    }

    /**
     * Gets the value of the dtlCheckNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtlCheckNumber() {
        return dtlCheckNumber;
    }

    /**
     * Sets the value of the dtlCheckNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtlCheckNumber(String value) {
        this.dtlCheckNumber = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

}
