//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 06:31:22 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paym_track_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trans_ref_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tran_status" type="{http://schema.pagibig.aas.gov}status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymTrackNum",
    "transRefNum",
    "tranStatus"
})
@XmlRootElement(name = "integ_pfm_post_ptn_statusResponse")
public class IntegPfmPostPtnStatusResponse {

    @XmlElement(name = "paym_track_num", required = true)
    protected String paymTrackNum;
    @XmlElement(name = "trans_ref_num", required = true)
    protected String transRefNum;
    @XmlElement(name = "tran_status", required = true)
    protected String tranStatus;

    /**
     * Gets the value of the paymTrackNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymTrackNum() {
        return paymTrackNum;
    }

    /**
     * Sets the value of the paymTrackNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymTrackNum(String value) {
        this.paymTrackNum = value;
    }

    /**
     * Gets the value of the transRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransRefNum() {
        return transRefNum;
    }

    /**
     * Sets the value of the transRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransRefNum(String value) {
        this.transRefNum = value;
    }

    /**
     * Gets the value of the tranStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranStatus() {
        return tranStatus;
    }

    /**
     * Sets the value of the tranStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranStatus(String value) {
        this.tranStatus = value;
    }

}
