//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 11:33:54 AM CST 
//


package gov.aas.pagibig.webservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acctg_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="account_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segment10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="journal_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="references_or_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pfr_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency_amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="payor_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="account_type_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payment_tracking_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="credit_memo_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clear_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ticket_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="value_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="percov_frm" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="percov_to" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="peso_amt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pay_source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="posted_by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date_posted" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="bank_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="check_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdr_check_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctgDate",
    "accountType",
    "segment1",
    "segment2",
    "segment3",
    "segment4",
    "segment5",
    "segment6",
    "segment7",
    "segment8",
    "segment9",
    "segment10",
    "journalName",
    "categoryName",
    "currencyCode",
    "amount",
    "referencesOrDescription",
    "transactionId",
    "pfrNo",
    "currencyAmount",
    "payorName",
    "transactionNumber",
    "accountTypeNumber",
    "paymentTrackingNumber",
    "creditMemoNumber",
    "clearDate",
    "ticketDate",
    "valueDate",
    "percovFrm",
    "percovTo",
    "pesoAmt",
    "paySource",
    "postedBy",
    "datePosted",
    "bankName",
    "checkNumber",
    "hdrCheckType",
    "filename"
})
@XmlRootElement(name = "integ_gl_post_journal_entries_to_gl_request_list")
public class IntegGlPostJournalEntriesToGlRequestList {

    @XmlElement(name = "acctg_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar acctgDate;
    @XmlElement(name = "account_type", required = true)
    protected String accountType;
    @XmlElement(required = true)
    protected String segment1;
    @XmlElement(required = true)
    protected String segment2;
    @XmlElement(required = true)
    protected String segment3;
    @XmlElement(required = true)
    protected String segment4;
    @XmlElement(required = true)
    protected String segment5;
    @XmlElement(required = true)
    protected String segment6;
    @XmlElement(required = true)
    protected String segment7;
    @XmlElement(required = true)
    protected String segment8;
    @XmlElement(required = true)
    protected String segment9;
    @XmlElement(required = true)
    protected String segment10;
    @XmlElement(name = "journal_name", required = true)
    protected String journalName;
    @XmlElement(name = "category_name", required = true)
    protected String categoryName;
    @XmlElement(name = "currency_code", required = true)
    protected String currencyCode;
    @XmlElement(required = true)
    protected BigDecimal amount;
    @XmlElement(name = "references_or_description", required = true)
    protected String referencesOrDescription;
    @XmlElement(name = "transaction_id", required = true)
    protected String transactionId;
    @XmlElement(name = "pfr_no", required = true)
    protected String pfrNo;
    @XmlElement(name = "currency_amount", required = true)
    protected BigDecimal currencyAmount;
    @XmlElement(name = "payor_name", required = true)
    protected String payorName;
    @XmlElement(name = "transaction_number", required = true)
    protected String transactionNumber;
    @XmlElement(name = "account_type_number", required = true)
    protected String accountTypeNumber;
    @XmlElement(name = "payment_tracking_number", required = true)
    protected String paymentTrackingNumber;
    @XmlElement(name = "credit_memo_number", required = true)
    protected String creditMemoNumber;
    @XmlElement(name = "clear_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar clearDate;
    @XmlElement(name = "ticket_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ticketDate;
    @XmlElement(name = "value_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar valueDate;
    @XmlElement(name = "percov_frm", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar percovFrm;
    @XmlElement(name = "percov_to", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar percovTo;
    @XmlElement(name = "peso_amt", required = true)
    protected BigDecimal pesoAmt;
    @XmlElement(name = "pay_source", required = true)
    protected String paySource;
    @XmlElement(name = "posted_by", required = true)
    protected String postedBy;
    @XmlElement(name = "date_posted", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePosted;
    @XmlElement(name = "bank_name", required = true)
    protected String bankName;
    @XmlElement(name = "check_number", required = true)
    protected String checkNumber;
    @XmlElement(name = "hdr_check_type", required = true)
    protected String hdrCheckType;
    @XmlElement(required = true)
    protected String filename;

    /**
     * Gets the value of the acctgDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcctgDate() {
        return acctgDate;
    }

    /**
     * Sets the value of the acctgDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcctgDate(XMLGregorianCalendar value) {
        this.acctgDate = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the segment1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment1() {
        return segment1;
    }

    /**
     * Sets the value of the segment1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment1(String value) {
        this.segment1 = value;
    }

    /**
     * Gets the value of the segment2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment2() {
        return segment2;
    }

    /**
     * Sets the value of the segment2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment2(String value) {
        this.segment2 = value;
    }

    /**
     * Gets the value of the segment3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment3() {
        return segment3;
    }

    /**
     * Sets the value of the segment3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment3(String value) {
        this.segment3 = value;
    }

    /**
     * Gets the value of the segment4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment4() {
        return segment4;
    }

    /**
     * Sets the value of the segment4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment4(String value) {
        this.segment4 = value;
    }

    /**
     * Gets the value of the segment5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment5() {
        return segment5;
    }

    /**
     * Sets the value of the segment5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment5(String value) {
        this.segment5 = value;
    }

    /**
     * Gets the value of the segment6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment6() {
        return segment6;
    }

    /**
     * Sets the value of the segment6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment6(String value) {
        this.segment6 = value;
    }

    /**
     * Gets the value of the segment7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment7() {
        return segment7;
    }

    /**
     * Sets the value of the segment7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment7(String value) {
        this.segment7 = value;
    }

    /**
     * Gets the value of the segment8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment8() {
        return segment8;
    }

    /**
     * Sets the value of the segment8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment8(String value) {
        this.segment8 = value;
    }

    /**
     * Gets the value of the segment9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment9() {
        return segment9;
    }

    /**
     * Sets the value of the segment9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment9(String value) {
        this.segment9 = value;
    }

    /**
     * Gets the value of the segment10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment10() {
        return segment10;
    }

    /**
     * Sets the value of the segment10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment10(String value) {
        this.segment10 = value;
    }

    /**
     * Gets the value of the journalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalName() {
        return journalName;
    }

    /**
     * Sets the value of the journalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalName(String value) {
        this.journalName = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the referencesOrDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencesOrDescription() {
        return referencesOrDescription;
    }

    /**
     * Sets the value of the referencesOrDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencesOrDescription(String value) {
        this.referencesOrDescription = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the pfrNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPfrNo() {
        return pfrNo;
    }

    /**
     * Sets the value of the pfrNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPfrNo(String value) {
        this.pfrNo = value;
    }

    /**
     * Gets the value of the currencyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrencyAmount() {
        return currencyAmount;
    }

    /**
     * Sets the value of the currencyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrencyAmount(BigDecimal value) {
        this.currencyAmount = value;
    }

    /**
     * Gets the value of the payorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayorName() {
        return payorName;
    }

    /**
     * Sets the value of the payorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayorName(String value) {
        this.payorName = value;
    }

    /**
     * Gets the value of the transactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * Sets the value of the transactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionNumber(String value) {
        this.transactionNumber = value;
    }

    /**
     * Gets the value of the accountTypeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountTypeNumber() {
        return accountTypeNumber;
    }

    /**
     * Sets the value of the accountTypeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountTypeNumber(String value) {
        this.accountTypeNumber = value;
    }

    /**
     * Gets the value of the paymentTrackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTrackingNumber() {
        return paymentTrackingNumber;
    }

    /**
     * Sets the value of the paymentTrackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTrackingNumber(String value) {
        this.paymentTrackingNumber = value;
    }

    /**
     * Gets the value of the creditMemoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditMemoNumber() {
        return creditMemoNumber;
    }

    /**
     * Sets the value of the creditMemoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditMemoNumber(String value) {
        this.creditMemoNumber = value;
    }

    /**
     * Gets the value of the clearDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClearDate() {
        return clearDate;
    }

    /**
     * Sets the value of the clearDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClearDate(XMLGregorianCalendar value) {
        this.clearDate = value;
    }

    /**
     * Gets the value of the ticketDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTicketDate() {
        return ticketDate;
    }

    /**
     * Sets the value of the ticketDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTicketDate(XMLGregorianCalendar value) {
        this.ticketDate = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValueDate(XMLGregorianCalendar value) {
        this.valueDate = value;
    }

    /**
     * Gets the value of the percovFrm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPercovFrm() {
        return percovFrm;
    }

    /**
     * Sets the value of the percovFrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPercovFrm(XMLGregorianCalendar value) {
        this.percovFrm = value;
    }

    /**
     * Gets the value of the percovTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPercovTo() {
        return percovTo;
    }

    /**
     * Sets the value of the percovTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPercovTo(XMLGregorianCalendar value) {
        this.percovTo = value;
    }

    /**
     * Gets the value of the pesoAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPesoAmt() {
        return pesoAmt;
    }

    /**
     * Sets the value of the pesoAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPesoAmt(BigDecimal value) {
        this.pesoAmt = value;
    }

    /**
     * Gets the value of the paySource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaySource() {
        return paySource;
    }

    /**
     * Sets the value of the paySource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaySource(String value) {
        this.paySource = value;
    }

    /**
     * Gets the value of the postedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostedBy() {
        return postedBy;
    }

    /**
     * Sets the value of the postedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostedBy(String value) {
        this.postedBy = value;
    }

    /**
     * Gets the value of the datePosted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePosted() {
        return datePosted;
    }

    /**
     * Sets the value of the datePosted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePosted(XMLGregorianCalendar value) {
        this.datePosted = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckNumber(String value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the hdrCheckType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdrCheckType() {
        return hdrCheckType;
    }

    /**
     * Sets the value of the hdrCheckType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdrCheckType(String value) {
        this.hdrCheckType = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

}
