//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 11:33:54 AM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.aas.pagibig.schema.ErrorType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paym_track_num" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="acc_type_code" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="acc_type_desc" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="acc_no" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="debit_memo" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="period" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="pay_allo" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="amount" type="{http://schema.pagibig.aas.gov}status"/>
 *         &lt;element name="error" type="{http://schema.pagibig.aas.gov}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymTrackNum",
    "accTypeCode",
    "accTypeDesc",
    "accNo",
    "debitMemo",
    "period",
    "payAllo",
    "amount",
    "error"
})
@XmlRootElement(name = "integ_pfm_get_ptn_acc_infoResponse")
public class IntegPfmGetPtnAccInfoResponse {

    @XmlElement(name = "paym_track_num", required = true)
    protected String paymTrackNum;
    @XmlElement(name = "acc_type_code", required = true)
    protected String accTypeCode;
    @XmlElement(name = "acc_type_desc", required = true)
    protected String accTypeDesc;
    @XmlElement(name = "acc_no", required = true)
    protected String accNo;
    @XmlElement(name = "debit_memo", required = true)
    protected String debitMemo;
    @XmlElement(required = true)
    protected String period;
    @XmlElement(name = "pay_allo", required = true)
    protected String payAllo;
    @XmlElement(required = true)
    protected String amount;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the paymTrackNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymTrackNum() {
        return paymTrackNum;
    }

    /**
     * Sets the value of the paymTrackNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymTrackNum(String value) {
        this.paymTrackNum = value;
    }

    /**
     * Gets the value of the accTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccTypeCode() {
        return accTypeCode;
    }

    /**
     * Sets the value of the accTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccTypeCode(String value) {
        this.accTypeCode = value;
    }

    /**
     * Gets the value of the accTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccTypeDesc() {
        return accTypeDesc;
    }

    /**
     * Sets the value of the accTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccTypeDesc(String value) {
        this.accTypeDesc = value;
    }

    /**
     * Gets the value of the accNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * Sets the value of the accNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccNo(String value) {
        this.accNo = value;
    }

    /**
     * Gets the value of the debitMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitMemo() {
        return debitMemo;
    }

    /**
     * Sets the value of the debitMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitMemo(String value) {
        this.debitMemo = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod(String value) {
        this.period = value;
    }

    /**
     * Gets the value of the payAllo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayAllo() {
        return payAllo;
    }

    /**
     * Sets the value of the payAllo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayAllo(String value) {
        this.payAllo = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
