//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 11:33:54 AM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.aas.pagibig.schema.ErrorType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dept_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="div_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="div_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error" type="{http://schema.pagibig.aas.gov}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deptCode",
    "divCode",
    "divName",
    "error"
})
@XmlRootElement(name = "integ_hris_get_div_dataResponse")
public class IntegHrisGetDivDataResponse {

    @XmlElement(name = "dept_code", required = true)
    protected String deptCode;
    @XmlElement(name = "div_code", required = true)
    protected String divCode;
    @XmlElement(name = "div_name", required = true)
    protected String divName;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the deptCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * Sets the value of the deptCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptCode(String value) {
        this.deptCode = value;
    }

    /**
     * Gets the value of the divCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivCode() {
        return divCode;
    }

    /**
     * Sets the value of the divCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivCode(String value) {
        this.divCode = value;
    }

    /**
     * Gets the value of the divName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivName() {
        return divName;
    }

    /**
     * Sets the value of the divName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivName(String value) {
        this.divName = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
