//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 04:14:11 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.aas.pagibig.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.aas.pagibig.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IntegPfmGetDatedPayResponse }
     * 
     */
    public IntegPfmGetDatedPayResponse createIntegPfmGetDatedPayResponse() {
        return new IntegPfmGetDatedPayResponse();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofDetailResponse }
     * 
     */
    public IntegOtcInsertAcqPofDetailResponse createIntegOtcInsertAcqPofDetailResponse() {
        return new IntegOtcInsertAcqPofDetailResponse();
    }

    /**
     * Create an instance of {@link IntegOtcGetHolidayInformationResponseList }
     * 
     */
    public IntegOtcGetHolidayInformationResponseList createIntegOtcGetHolidayInformationResponseList() {
        return new IntegOtcGetHolidayInformationResponseList();
    }

    /**
     * Create an instance of {@link IntegOtcUpdatePofStatusResponse }
     * 
     */
    public IntegOtcUpdatePofStatusResponse createIntegOtcUpdatePofStatusResponse() {
        return new IntegOtcUpdatePofStatusResponse();
    }

    /**
     * Create an instance of {@link IntegHrGetBrDetailsRequest }
     * 
     */
    public IntegHrGetBrDetailsRequest createIntegHrGetBrDetailsRequest() {
        return new IntegHrGetBrDetailsRequest();
    }

    /**
     * Create an instance of {@link IntegCmsGetDuePdcSummaryResponseList }
     * 
     */
    public IntegCmsGetDuePdcSummaryResponseList createIntegCmsGetDuePdcSummaryResponseList() {
        return new IntegCmsGetDuePdcSummaryResponseList();
    }

    /**
     * Create an instance of {@link IntegHrGetUnitInfoRequest }
     * 
     */
    public IntegHrGetUnitInfoRequest createIntegHrGetUnitInfoRequest() {
        return new IntegHrGetUnitInfoRequest();
    }

    /**
     * Create an instance of {@link IntegPfmGetPtnAccInfoResponse }
     * 
     */
    public IntegPfmGetPtnAccInfoResponse createIntegPfmGetPtnAccInfoResponse() {
        return new IntegPfmGetPtnAccInfoResponse();
    }

    /**
     * Create an instance of {@link IntegPfmGetPtnAccInfoRequest }
     * 
     */
    public IntegPfmGetPtnAccInfoRequest createIntegPfmGetPtnAccInfoRequest() {
        return new IntegPfmGetPtnAccInfoRequest();
    }

    /**
     * Create an instance of {@link IntegPfmGetPtnInfoResponse }
     * 
     */
    public IntegPfmGetPtnInfoResponse createIntegPfmGetPtnInfoResponse() {
        return new IntegPfmGetPtnInfoResponse();
    }

    /**
     * Create an instance of {@link IntegGlPostJournalEntriesToGlResponse }
     * 
     */
    public IntegGlPostJournalEntriesToGlResponse createIntegGlPostJournalEntriesToGlResponse() {
        return new IntegGlPostJournalEntriesToGlResponse();
    }

    /**
     * Create an instance of {@link IntegPfmGetPtnInfoRequest }
     * 
     */
    public IntegPfmGetPtnInfoRequest createIntegPfmGetPtnInfoRequest() {
        return new IntegPfmGetPtnInfoRequest();
    }

    /**
     * Create an instance of {@link IntegApRequestForPaymentList }
     * 
     */
    public IntegApRequestForPaymentList createIntegApRequestForPaymentList() {
        return new IntegApRequestForPaymentList();
    }

    /**
     * Create an instance of {@link IntegAasGetForeStatusRequest }
     * 
     */
    public IntegAasGetForeStatusRequest createIntegAasGetForeStatusRequest() {
        return new IntegAasGetForeStatusRequest();
    }

    /**
     * Create an instance of {@link TestingPostingRequest }
     * 
     */
    public TestingPostingRequest createTestingPostingRequest() {
        return new TestingPostingRequest();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofHeaderResponse }
     * 
     */
    public IntegOtcInsertAcqPofHeaderResponse createIntegOtcInsertAcqPofHeaderResponse() {
        return new IntegOtcInsertAcqPofHeaderResponse();
    }

    /**
     * Create an instance of {@link IntegTfmsGetDayRatesRequest }
     * 
     */
    public IntegTfmsGetDayRatesRequest createIntegTfmsGetDayRatesRequest() {
        return new IntegTfmsGetDayRatesRequest();
    }

    /**
     * Create an instance of {@link IntegOtcGetUserDetailsRequest }
     * 
     */
    public IntegOtcGetUserDetailsRequest createIntegOtcGetUserDetailsRequest() {
        return new IntegOtcGetUserDetailsRequest();
    }

    /**
     * Create an instance of {@link IntegApRequestForPaymentResponse }
     * 
     */
    public IntegApRequestForPaymentResponse createIntegApRequestForPaymentResponse() {
        return new IntegApRequestForPaymentResponse();
    }

    /**
     * Create an instance of {@link IntegPfmPostPtnStatusRequest }
     * 
     */
    public IntegPfmPostPtnStatusRequest createIntegPfmPostPtnStatusRequest() {
        return new IntegPfmPostPtnStatusRequest();
    }

    /**
     * Create an instance of {@link IntegOtcPostPdcpaymStatusRequest }
     * 
     */
    public IntegOtcPostPdcpaymStatusRequest createIntegOtcPostPdcpaymStatusRequest() {
        return new IntegOtcPostPdcpaymStatusRequest();
    }

    /**
     * Create an instance of {@link IntegOtcGetPofHeaderResponse }
     * 
     */
    public IntegOtcGetPofHeaderResponse createIntegOtcGetPofHeaderResponse() {
        return new IntegOtcGetPofHeaderResponse();
    }

    /**
     * Create an instance of {@link IntegCmsGetDuePdcSummaryResponse }
     * 
     */
    public IntegCmsGetDuePdcSummaryResponse createIntegCmsGetDuePdcSummaryResponse() {
        return new IntegCmsGetDuePdcSummaryResponse();
    }

    /**
     * Create an instance of {@link IntegOtcGetPofDetailRequest }
     * 
     */
    public IntegOtcGetPofDetailRequest createIntegOtcGetPofDetailRequest() {
        return new IntegOtcGetPofDetailRequest();
    }

    /**
     * Create an instance of {@link IntegOtcPostCollectionsAndOtherCollectionsList }
     * 
     */
    public IntegOtcPostCollectionsAndOtherCollectionsList createIntegOtcPostCollectionsAndOtherCollectionsList() {
        return new IntegOtcPostCollectionsAndOtherCollectionsList();
    }

    /**
     * Create an instance of {@link IntegPfmGetCmPayDetRequest }
     * 
     */
    public IntegPfmGetCmPayDetRequest createIntegPfmGetCmPayDetRequest() {
        return new IntegPfmGetCmPayDetRequest();
    }

    /**
     * Create an instance of {@link IntegAasGetForeStatusResponse }
     * 
     */
    public IntegAasGetForeStatusResponse createIntegAasGetForeStatusResponse() {
        return new IntegAasGetForeStatusResponse();
    }

    /**
     * Create an instance of {@link IntegOtcGetHolidayInformationRequest }
     * 
     */
    public IntegOtcGetHolidayInformationRequest createIntegOtcGetHolidayInformationRequest() {
        return new IntegOtcGetHolidayInformationRequest();
    }

    /**
     * Create an instance of {@link IntegOtcGetUserDetailsResponse }
     * 
     */
    public IntegOtcGetUserDetailsResponse createIntegOtcGetUserDetailsResponse() {
        return new IntegOtcGetUserDetailsResponse();
    }

    /**
     * Create an instance of {@link IntegOtcGetHolidayInformationResponse }
     * 
     */
    public IntegOtcGetHolidayInformationResponse createIntegOtcGetHolidayInformationResponse() {
        return new IntegOtcGetHolidayInformationResponse();
    }

    /**
     * Create an instance of {@link IntegPfmPostPtnStatusResponse }
     * 
     */
    public IntegPfmPostPtnStatusResponse createIntegPfmPostPtnStatusResponse() {
        return new IntegPfmPostPtnStatusResponse();
    }

    /**
     * Create an instance of {@link IntegPfmGetDatedPayRequest }
     * 
     */
    public IntegPfmGetDatedPayRequest createIntegPfmGetDatedPayRequest() {
        return new IntegPfmGetDatedPayRequest();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofDetailRequest }
     * 
     */
    public IntegOtcInsertAcqPofDetailRequest createIntegOtcInsertAcqPofDetailRequest() {
        return new IntegOtcInsertAcqPofDetailRequest();
    }

    /**
     * Create an instance of {@link IntegHrGetBrDetailsResponseList }
     * 
     */
    public IntegHrGetBrDetailsResponseList createIntegHrGetBrDetailsResponseList() {
        return new IntegHrGetBrDetailsResponseList();
    }

    /**
     * Create an instance of {@link IntegHrGetUnitInfoResponse }
     * 
     */
    public IntegHrGetUnitInfoResponse createIntegHrGetUnitInfoResponse() {
        return new IntegHrGetUnitInfoResponse();
    }

    /**
     * Create an instance of {@link IntegCmsGetBranchPfrNoSeriesResponse }
     * 
     */
    public IntegCmsGetBranchPfrNoSeriesResponse createIntegCmsGetBranchPfrNoSeriesResponse() {
        return new IntegCmsGetBranchPfrNoSeriesResponse();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofHeaderSampleResponse }
     * 
     */
    public IntegOtcInsertAcqPofHeaderSampleResponse createIntegOtcInsertAcqPofHeaderSampleResponse() {
        return new IntegOtcInsertAcqPofHeaderSampleResponse();
    }

    /**
     * Create an instance of {@link IntegOtcPostCollectionsAndOtherCollectionsResponse }
     * 
     */
    public IntegOtcPostCollectionsAndOtherCollectionsResponse createIntegOtcPostCollectionsAndOtherCollectionsResponse() {
        return new IntegOtcPostCollectionsAndOtherCollectionsResponse();
    }

    /**
     * Create an instance of {@link IntegOtcUpdatePofStatusRequest }
     * 
     */
    public IntegOtcUpdatePofStatusRequest createIntegOtcUpdatePofStatusRequest() {
        return new IntegOtcUpdatePofStatusRequest();
    }

    /**
     * Create an instance of {@link IntegOtcPostPdcpaymStatusResponse }
     * 
     */
    public IntegOtcPostPdcpaymStatusResponse createIntegOtcPostPdcpaymStatusResponse() {
        return new IntegOtcPostPdcpaymStatusResponse();
    }

    /**
     * Create an instance of {@link IntegOtcGetPofDetailResponse }
     * 
     */
    public IntegOtcGetPofDetailResponse createIntegOtcGetPofDetailResponse() {
        return new IntegOtcGetPofDetailResponse();
    }

    /**
     * Create an instance of {@link IntegCmsGetBranchPfrNoSeriesRequest }
     * 
     */
    public IntegCmsGetBranchPfrNoSeriesRequest createIntegCmsGetBranchPfrNoSeriesRequest() {
        return new IntegCmsGetBranchPfrNoSeriesRequest();
    }

    /**
     * Create an instance of {@link IntegPfmGetCmPayDetResponse }
     * 
     */
    public IntegPfmGetCmPayDetResponse createIntegPfmGetCmPayDetResponse() {
        return new IntegPfmGetCmPayDetResponse();
    }

    /**
     * Create an instance of {@link IntegHrGetUnitInfoResponseList }
     * 
     */
    public IntegHrGetUnitInfoResponseList createIntegHrGetUnitInfoResponseList() {
        return new IntegHrGetUnitInfoResponseList();
    }

    /**
     * Create an instance of {@link IntegCmsGetDuePdcSummaryRequest }
     * 
     */
    public IntegCmsGetDuePdcSummaryRequest createIntegCmsGetDuePdcSummaryRequest() {
        return new IntegCmsGetDuePdcSummaryRequest();
    }

    /**
     * Create an instance of {@link IntegTfmsGetDayRatesResponse }
     * 
     */
    public IntegTfmsGetDayRatesResponse createIntegTfmsGetDayRatesResponse() {
        return new IntegTfmsGetDayRatesResponse();
    }

    /**
     * Create an instance of {@link IntegHrGetBrDetailsResponse }
     * 
     */
    public IntegHrGetBrDetailsResponse createIntegHrGetBrDetailsResponse() {
        return new IntegHrGetBrDetailsResponse();
    }

    /**
     * Create an instance of {@link TestingPostingResponse }
     * 
     */
    public TestingPostingResponse createTestingPostingResponse() {
        return new TestingPostingResponse();
    }

    /**
     * Create an instance of {@link IntegGlPostJournalEntriesToGlRequestList }
     * 
     */
    public IntegGlPostJournalEntriesToGlRequestList createIntegGlPostJournalEntriesToGlRequestList() {
        return new IntegGlPostJournalEntriesToGlRequestList();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofHeaderRequest }
     * 
     */
    public IntegOtcInsertAcqPofHeaderRequest createIntegOtcInsertAcqPofHeaderRequest() {
        return new IntegOtcInsertAcqPofHeaderRequest();
    }

    /**
     * Create an instance of {@link IntegOtcPostCollectionsAndOtherCollectionsRequest }
     * 
     */
    public IntegOtcPostCollectionsAndOtherCollectionsRequest createIntegOtcPostCollectionsAndOtherCollectionsRequest() {
        return new IntegOtcPostCollectionsAndOtherCollectionsRequest();
    }

    /**
     * Create an instance of {@link IntegOtcGetPofHeaderRequest }
     * 
     */
    public IntegOtcGetPofHeaderRequest createIntegOtcGetPofHeaderRequest() {
        return new IntegOtcGetPofHeaderRequest();
    }

    /**
     * Create an instance of {@link IntegOtcCheckPofStatusRequest }
     * 
     */
    public IntegOtcCheckPofStatusRequest createIntegOtcCheckPofStatusRequest() {
        return new IntegOtcCheckPofStatusRequest();
    }

    /**
     * Create an instance of {@link IntegOtcInsertAcqPofHeaderSampleRequest }
     * 
     */
    public IntegOtcInsertAcqPofHeaderSampleRequest createIntegOtcInsertAcqPofHeaderSampleRequest() {
        return new IntegOtcInsertAcqPofHeaderSampleRequest();
    }

    /**
     * Create an instance of {@link IntegOtcCheckPofStatusResponse }
     * 
     */
    public IntegOtcCheckPofStatusResponse createIntegOtcCheckPofStatusResponse() {
        return new IntegOtcCheckPofStatusResponse();
    }

    /**
     * Create an instance of {@link IntegPfmGetPtnInfoResponseList }
     * 
     */
    public IntegPfmGetPtnInfoResponseList createIntegPfmGetPtnInfoResponseList() {
        return new IntegPfmGetPtnInfoResponseList();
    }

    /**
     * Create an instance of {@link IntegApRequestForPaymentRequest }
     * 
     */
    public IntegApRequestForPaymentRequest createIntegApRequestForPaymentRequest() {
        return new IntegApRequestForPaymentRequest();
    }

    /**
     * Create an instance of {@link IntegGlPostJournalEntriesToGlRequest }
     * 
     */
    public IntegGlPostJournalEntriesToGlRequest createIntegGlPostJournalEntriesToGlRequest() {
        return new IntegGlPostJournalEntriesToGlRequest();
    }

}
