//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 05:31:12 PM CST 
//


package gov.aas.pagibig.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source_sys_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tester_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tester_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tester_add" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceSysId",
    "testerId",
    "testerName",
    "testerAdd"
})
@XmlRootElement(name = "testing_postingRequest")
public class TestingPostingRequest {

    @XmlElement(name = "source_sys_id", required = true)
    protected String sourceSysId;
    @XmlElement(name = "tester_id", required = true)
    protected String testerId;
    @XmlElement(name = "tester_name", required = true)
    protected String testerName;
    @XmlElement(name = "tester_add", required = true)
    protected String testerAdd;

    /**
     * Gets the value of the sourceSysId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSysId() {
        return sourceSysId;
    }

    /**
     * Sets the value of the sourceSysId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSysId(String value) {
        this.sourceSysId = value;
    }

    /**
     * Gets the value of the testerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesterId() {
        return testerId;
    }

    /**
     * Sets the value of the testerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesterId(String value) {
        this.testerId = value;
    }

    /**
     * Gets the value of the testerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesterName() {
        return testerName;
    }

    /**
     * Sets the value of the testerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesterName(String value) {
        this.testerName = value;
    }

    /**
     * Gets the value of the testerAdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesterAdd() {
        return testerAdd;
    }

    /**
     * Sets the value of the testerAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesterAdd(String value) {
        this.testerAdd = value;
    }

}
