package gov.aas.pagibig.webservice.core;
// Generated Oct 23, 2014 4:07:22 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TBLHolidayInformatio generated by hbm2java
 */
@Entity
@Table(name="tb_get_holiday_info")
@NamedQueries(@NamedQuery(name = "TBLHolidayInformation.getHolidayInformation", query = "SELECT tbl FROM TBLHolidayInformation tbl WHERE tbl.holidayDate BETWEEN :from AND :to"))
public class TBLHolidayInformation  implements java.io.Serializable {


     private String holidayId;
     private Date holidayDate;
     private String errorFlag;
     private String holidayDesc;
     private Integer year;
     private String status;

    public TBLHolidayInformation() {
    }

	
    public TBLHolidayInformation(String holidayId, Date holidayDate) {
        this.holidayId = holidayId;
        this.holidayDate = holidayDate;
    }
    public TBLHolidayInformation(String holidayId, Date holidayDate, String errorFlag, String holidayDesc, Integer year, String status) {
       this.holidayId = holidayId;
       this.holidayDate = holidayDate;
       this.errorFlag = errorFlag;
       this.holidayDesc = holidayDesc;
       this.year = year;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="holiday_id", unique=true, nullable=false, length=10)
    public String getHolidayId() {
        return this.holidayId;
    }
    
    public void setHolidayId(String holidayId) {
        this.holidayId = holidayId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="holiday_date", nullable=false, length=10)
    public Date getHolidayDate() {
        return this.holidayDate;
    }
    
    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }
    
    @Column(name="error_flag", length=1)
    public String getErrorFlag() {
        return this.errorFlag;
    }
    
    public void setErrorFlag(String errorFlag) {
        this.errorFlag = errorFlag;
    }
    
    @Column(name="holiday_desc", length=250)
    public String getHolidayDesc() {
        return this.holidayDesc;
    }
    
    public void setHolidayDesc(String holidayDesc) {
        this.holidayDesc = holidayDesc;
    }
    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


